//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QTxtConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QTxtConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Number&gt;         := &lt;Digit&gt;+0
        ///&lt;Quest, [N]&gt;     := &lt;BR&gt;&lt;SP&gt;*[N=]&lt;Number&gt;([line].|&lt;BR&gt;&amp;!(&lt;BR&gt;&lt;SP&gt;*&lt;Number&gt;))*
        ///&lt;Tail, [N], [M]&gt; := [X = N * M][m][Quest=]&lt;Quest, [X]&gt;([M1 = M + 1]&lt;Tail, [N], [M1]&gt;|)
        ///&lt;Tail,{0},{1}&gt;      =&gt; [matches, Tail].
        /// </summary>
        public static string AppendRules {
            get {
                return ResourceManager.GetString("AppendRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Number&gt; := &lt;d&gt;+0
        ///&lt;Quest $n&gt; := &lt;BR&gt;&lt;SP&gt;*($n :: &lt;Number&gt;)([one]&lt;s&gt;|&lt;BR&gt;&amp;!(&lt;BR&gt;&lt;SP&gt;*&lt;Number&gt;))*
        ///$q :: &lt;Quest $x&gt; =&gt; $q
        ///$x :: &lt;s&gt; =&gt; $x
        ///$x =&gt; $x.
        /// </summary>
        public static string ExtractorRules2 {
            get {
                return ResourceManager.GetString("ExtractorRules2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Number&gt;         := &lt;d&gt;+0
        ///&lt;Quest $n&gt;     := &lt;BR&gt;&lt;SP&gt;*($n :: &lt;Number&gt;)([one]&lt;s&gt;|&lt;BR&gt;&amp;!(&lt;BR&gt;&lt;SP&gt;*&lt;Number&gt;))*
        ///&lt;Tail $n $m&gt; := [$x = $n * $m][m]&lt;Quest $x&gt;([$m1 = $m + 1]&lt;Tail $n $m1&gt;|[$m &gt; 2])
        ///&lt;Theme&gt;          := [m]&lt;Quest $n&gt;&lt;Tail $n 2&gt;
        ///&lt;Head&gt;           := ([one]&lt;s&gt;|&lt;BR&gt;&amp;!(&lt;BR&gt;&lt;SP&gt;*&lt;Number&gt;))*
        ///[m]&lt;Theme&gt;      =&gt; $(match Theme)
        ///[m]&lt;Head&gt; =&gt; $(match Head).
        /// </summary>
        public static string QuestsExtractorRules3 {
            get {
                return ResourceManager.GetString("QuestsExtractorRules3", resourceCulture);
            }
        }
    }
}
