//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автор: Владимир Хиль.
        /// </summary>
        public static string About_Author {
            get {
                return ResourceManager.GetString("About_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Композитор.
        /// </summary>
        public static string About_Composer {
            get {
                return ResourceManager.GetString("About_Composer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дизайнер: Александр Кузнецов.
        /// </summary>
        public static string About_Design {
            get {
                return ResourceManager.GetString("About_Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображения участников находятся в общественном достоянии и взяты с сайта wikipedia.org.
        /// </summary>
        public static string About_Images {
            get {
                return ResourceManager.GetString("About_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайт программы.
        /// </summary>
        public static string About_Site {
            get {
                return ResourceManager.GetString("About_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Компьютер.
        /// </summary>
        public static string AccountTypes_Computer {
            get {
                return ResourceManager.GetString("AccountTypes_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Человек.
        /// </summary>
        public static string AccountTypes_Human {
            get {
                return ResourceManager.GetString("AccountTypes_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить стол.
        /// </summary>
        public static string AddTable {
            get {
                return ResourceManager.GetString("AddTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: ВА-БАНК на вопросе 1 категории.
        /// </summary>
        public static string AllInOnQuestion1 {
            get {
                return ResourceManager.GetString("AllInOnQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: ВА-БАНК на вопросе 5 категории.
        /// </summary>
        public static string AllInOnQuestion5 {
            get {
                return ResourceManager.GetString("AllInOnQuestion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверка ответа.
        /// </summary>
        public static string AnswerCheck {
            get {
                return ResourceManager.GetString("AnswerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будут отображаться внизу экрана.
        /// </summary>
        public static string AnswersAtBottom {
            get {
                return ResourceManager.GetString("AnswersAtBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я прав!.
        /// </summary>
        public static string Apellate_Right {
            get {
                return ResourceManager.GetString("Apellate_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я ответил верно.
        /// </summary>
        public static string Apellate_Right_Hint {
            get {
                return ResourceManager.GetString("Apellate_Right_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я против!.
        /// </summary>
        public static string Apellate_Wrong {
            get {
                return ResourceManager.GetString("Apellate_Wrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другой ответил неверно.
        /// </summary>
        public static string Apellate_Wrong_Hint {
            get {
                return ResourceManager.GetString("Apellate_Wrong_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык приложения.
        /// </summary>
        public static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки приложения.
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тема.
        /// </summary>
        public static string AppTheme {
            get {
                return ResourceManager.GetString("AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по возрастанию.
        /// </summary>
        public static string Ascending {
            get {
                return ResourceManager.GetString("Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на за.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Авторы.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аватар….
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забанить.
        /// </summary>
        public static string Ban {
            get {
                return ResourceManager.GetString("Ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Базовая стоимость вопроса в случайном пакете.
        /// </summary>
        public static string BaseCostForRandomPackage {
            get {
                return ResourceManager.GetString("BaseCostForRandomPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рождения.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Смелость.
        /// </summary>
        public static string Bravery {
            get {
                return ResourceManager.GetString("Bravery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена готовности.
        /// </summary>
        public static string CancelReady {
            get {
                return ResourceManager.GetString("CancelReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость Вопроса с секретом.
        /// </summary>
        public static string CatCost {
            get {
                return ResourceManager.GetString("CatCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категории.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить тип на Компьютер.
        /// </summary>
        public static string ChangeToComputer {
            get {
                return ResourceManager.GetString("ChangeToComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить тип на Человек.
        /// </summary>
        public static string ChangeToHuman {
            get {
                return ResourceManager.GetString("ChangeToHuman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cимволов в секунду.
        /// </summary>
        public static string CharactersPerSecond {
            get {
                return ResourceManager.GetString("CharactersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Общее.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключиться.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создана.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число вопросов в конце раунда для мобилизации.
        /// </summary>
        public static string CriticalQuestionsCount {
            get {
                return ResourceManager.GetString("CriticalQuestionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на % своей суммы от денег лидера для мобилизации.
        /// </summary>
        public static string CriticalSumPartition {
            get {
                return ResourceManager.GetString("CriticalSumPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (по умолчанию).
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Будут использованы настройки по умолчанию..
        /// </summary>
        public static string DefaultSettingsWillBeUsed {
            get {
                return ResourceManager.GetString("DefaultSettingsWillBeUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить стол.
        /// </summary>
        public static string DeleteTable {
            get {
                return ResourceManager.GetString("DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя нажимать на кнопку до окончания чтения вопроса.
        /// </summary>
        public static string DenyPressWhileReading {
            get {
                return ResourceManager.GetString("DenyPressWhileReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на по убыванию.
        /// </summary>
        public static string Descending {
            get {
                return ResourceManager.GetString("Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поблагодарить автора….
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не отправлять.
        /// </summary>
        public static string DoNotSendReport {
            get {
                return ResourceManager.GetString("DoNotSendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Английский.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВХОД В ИГРУ.
        /// </summary>
        public static string Entrance {
            get {
                return ResourceManager.GetString("Entrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось запустить игру, так как повреждена система отрисовки DirectX 9.
        /// </summary>
        public static string Error_DirectXBroken {
            get {
                return ResourceManager.GetString("Error_DirectXBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось запустить игру, так как файлы игры повреждены.
        /// </summary>
        public static string Error_FilesBroken {
            get {
                return ResourceManager.GetString("Error_FilesBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно памяти для запуска программы!.
        /// </summary>
        public static string Error_IncifficientResources {
            get {
                return ResourceManager.GetString("Error_IncifficientResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно памяти для выполнения программы!.
        /// </summary>
        public static string Error_IncifficientResourcesForExecution {
            get {
                return ResourceManager.GetString("Error_IncifficientResourcesForExecution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось создать главное окно игры! Похоже, на вашем компьютере повреждена среда выполнения программ. Попробуйте переустановить .NET Framework 4..
        /// </summary>
        public static string Error_NetBroken {
            get {
                return ResourceManager.GetString("Error_NetBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обнаружено повреждение операционной системы. Запуск игры невозможен..
        /// </summary>
        public static string Error_OSBroken {
            get {
                return ResourceManager.GetString("Error_OSBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось создать главное окно игры! Похоже, на вашем компьютере повреждена среда выполнения программ.
        /// </summary>
        public static string Error_RuntimeBroken {
            get {
                return ResourceManager.GetString("Error_RuntimeBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при загрузке настроек программы.
        /// </summary>
        public static string Error_SettingsLoading {
            get {
                return ResourceManager.GetString("Error_SettingsLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении настроек программы.
        /// </summary>
        public static string Error_SettingsSaving {
            get {
                return ResourceManager.GetString("Error_SettingsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка с системными шрифтами. Запуск игры невозможен.
        /// </summary>
        public static string Error_Typography {
            get {
                return ResourceManager.GetString("Error_Typography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка старта игры, связанная с Windows Automation. Попробуйте установить обновления для своей операционной системы, для .NET Framework 4 или установить библиотеку API Windows Automation (ссылка находится на странице игры). Если ничего не поможет, свяжитесь, пожалуйста, с автором игры..
        /// </summary>
        public static string Error_WindowsAutomationBroken {
            get {
                return ResourceManager.GetString("Error_WindowsAutomationBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опишите, пожалуйста, ваши действия в момент возникновения ошибки.
        /// </summary>
        public static string ErrorDescribe {
            get {
                return ResourceManager.GetString("ErrorDescribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта ошибка исправлена в новой версии программы. Обновитесь, пожалуйста..
        /// </summary>
        public static string ErrorFixed {
            get {
                return ResourceManager.GetString("ErrorFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка в .NET Framework: {0}. Попробуйте установить обновления операционной системы или переустановить .NET Framework..
        /// </summary>
        public static string ErrorNET {
            get {
                return ResourceManager.GetString("ErrorNET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эта ошибка не воспроизводится. Если вы можете её гарантированно воспроизвести, свяжитесь с автором, пожалуйста..
        /// </summary>
        public static string ErrorNotReproduced {
            get {
                return ResourceManager.GetString("ErrorNotReproduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эрудиция.
        /// </summary>
        public static string Erudition {
            get {
                return ResourceManager.GetString("Erudition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Exit_Button {
            get {
                return ResourceManager.GetString("Exit_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход из игры.
        /// </summary>
        public static string ExitGame {
            get {
                return ResourceManager.GetString("ExitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действительно выйти?.
        /// </summary>
        public static string ExitPrompt {
            get {
                return ResourceManager.GetString("ExitPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фальстарты.
        /// </summary>
        public static string FalseStart {
            get {
                return ResourceManager.GetString("FalseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В приложении возникла неустранимая ошибка. Программа будет закрыта. Отправить информацию об ошибке автору?.
        /// </summary>
        public static string FatalErrorMessage {
            get {
                return ResourceManager.GetString("FatalErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечания и предложения….
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл….
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слишком большой файл (больше 1 Мб)!.
        /// </summary>
        public static string FileLarger1Mb {
            get {
                return ResourceManager.GetString("FileLarger1Mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (все).
        /// </summary>
        public static string Filter_All {
            get {
                return ResourceManager.GetString("Filter_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (не задано).
        /// </summary>
        public static string Filter_NotSet {
            get {
                return ResourceManager.GetString("Filter_NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НАЧАТЬ ИГРУ.
        /// </summary>
        public static string ForceStartGame {
            get {
                return ResourceManager.GetString("ForceStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать, не дожидаясь готовности участников.
        /// </summary>
        public static string ForceStartGame_Hint {
            get {
                return ResourceManager.GetString("ForceStartGame_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дальше.
        /// </summary>
        public static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Освободить.
        /// </summary>
        public static string Free {
            get {
                return ResourceManager.GetString("Free", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полноэкранный режим.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игровая кнопка.
        /// </summary>
        public static string GameButton_Hint {
            get {
                return ResourceManager.GetString("GameButton_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Клавиша игровой кнопки.
        /// </summary>
        public static string GameButtonKey {
            get {
                return ResourceManager.GetString("GameButtonKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление игрой.
        /// </summary>
        public static string GameManagement {
            get {
                return ResourceManager.GetString("GameManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Упрощённая.
        /// </summary>
        public static string GameModes_Sport {
            get {
                return ResourceManager.GetString("GameModes_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классическая.
        /// </summary>
        public static string GameModes_Tv {
            get {
                return ResourceManager.GetString("GameModes_Tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название игры.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игрок.
        /// </summary>
        public static string GameRole_Player {
            get {
                return ResourceManager.GetString("GameRole_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведущий.
        /// </summary>
        public static string GameRole_Showman {
            get {
                return ResourceManager.GetString("GameRole_Showman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зритель.
        /// </summary>
        public static string GameRole_Viewer {
            get {
                return ResourceManager.GetString("GameRole_Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила игры.
        /// </summary>
        public static string GameRules {
            get {
                return ResourceManager.GetString("GameRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стиль игры.
        /// </summary>
        public static string GameStyle {
            get {
                return ResourceManager.GetString("GameStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на игровым столом.
        /// </summary>
        public static string GameTable {
            get {
                return ResourceManager.GetString("GameTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип игры.
        /// </summary>
        public static string GameType {
            get {
                return ResourceManager.GetString("GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: отдать &quot;Вопрос с секретом&quot; тому, у кого меньше денег.
        /// </summary>
        public static string GiveCatToWorst {
            get {
                return ResourceManager.GetString("GiveCatToWorst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь….
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help_ru.xps.
        /// </summary>
        public static string HelpFile {
            get {
                return ResourceManager.GetString("HelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть чат.
        /// </summary>
        public static string HideChat {
            get {
                return ResourceManager.GetString("HideChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сообщать ведущему правильные ответы заранее.
        /// </summary>
        public static string HintShowman {
            get {
                return ResourceManager.GetString("HintShowman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хост.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображения.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти игроком.
        /// </summary>
        public static string JoinAsPlayer {
            get {
                return ResourceManager.GetString("JoinAsPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти ведущим.
        /// </summary>
        public static string JoinAsShowman {
            get {
                return ResourceManager.GetString("JoinAsShowman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти зрителем.
        /// </summary>
        public static string JoinAsViewer {
            get {
                return ResourceManager.GetString("JoinAsViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замечания.
        /// </summary>
        public static string JumpList_Feedback {
            get {
                return ResourceManager.GetString("JumpList_Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Написать замечания автору игры.
        /// </summary>
        public static string JumpList_Feedback_Hint {
            get {
                return ResourceManager.GetString("JumpList_Feedback_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Помощь.
        /// </summary>
        public static string JumpList_Help {
            get {
                return ResourceManager.GetString("JumpList_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть файл помощи.
        /// </summary>
        public static string JumpList_Help_Hint {
            get {
                return ResourceManager.GetString("JumpList_Help_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логи.
        /// </summary>
        public static string JumpList_Logs {
            get {
                return ResourceManager.GetString("JumpList_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку логов игры.
        /// </summary>
        public static string JumpList_Logs_Hint {
            get {
                return ResourceManager.GetString("JumpList_Logs_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выгнать.
        /// </summary>
        public static string Kick {
            get {
                return ResourceManager.GetString("Kick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лицензии.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Межстрочный интервал в вопросе.
        /// </summary>
        public static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на /SIGame;component/Resources/vk_logo.png.
        /// </summary>
        public static string LinkLogo {
            get {
                return ResourceManager.GetString("LinkLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружать мультимедиа со сторонних ресурсов.
        /// </summary>
        public static string LoadExternalMedia {
            get {
                return ResourceManager.GetString("LoadExternalMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для игры по локальной сети.
        /// </summary>
        public static string LocalNetworkOnly {
            get {
                return ResourceManager.GetString("LocalNetworkOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логика.
        /// </summary>
        public static string Logic {
            get {
                return ResourceManager.GetString("Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НИКНЕЙМ.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВОЙТИ.
        /// </summary>
        public static string Logon {
            get {
                return ResourceManager.GetString("Logon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логи….
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основной фон.
        /// </summary>
        public static string MainBackground {
            get {
                return ResourceManager.GetString("MainBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия главного меню.
        /// </summary>
        public static string MainMenuSound {
            get {
                return ResourceManager.GetString("MainMenuSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основной.
        /// </summary>
        public static string MainPort {
            get {
                return ResourceManager.GetString("MainPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на мужчина.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление ходом игры.
        /// </summary>
        public static string Manage_Hint {
            get {
                return ResourceManager.GetString("Manage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управляемая игра.
        /// </summary>
        public static string ManagedGame {
            get {
                return ResourceManager.GetString("ManagedGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра продолжается только по нажатию кнопки &quot;Дальше&quot;.
        /// </summary>
        public static string ManagedGame_Hint {
            get {
                return ResourceManager.GetString("ManagedGame_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление.
        /// </summary>
        public static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Порт изображений и мультимедиа-вопросов.
        /// </summary>
        public static string MediaPort {
            get {
                return ResourceManager.GetString("MediaPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на СООБЩЕНИЯ.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переместить….
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мультимедиа.
        /// </summary>
        public static string MultimediaPort {
            get {
                return ResourceManager.GetString("MultimediaPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повреждена среда выполнения программы! Переустановите .NET Framework 4.6..
        /// </summary>
        public static string NETFrameworkCorrupted {
            get {
                return ResourceManager.GetString("NETFrameworkCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для создания сетевой игры нужно играть по локальной сети, иметь реальный IP или настроить NAT.
        /// </summary>
        public static string NetworkGameHint {
            get {
                return ResourceManager.GetString("NetworkGameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Локальная сеть.
        /// </summary>
        public static string NetworkGameType_DirectConnection {
            get {
                return ResourceManager.GetString("NetworkGameType_DirectConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интернет.
        /// </summary>
        public static string NetworkGameType_NetworkGameServer {
            get {
                return ResourceManager.GetString("NetworkGameType_NetworkGameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НОВАЯ ИГРА.
        /// </summary>
        public static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующий.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Следующий раунд.
        /// </summary>
        public static string NextRound {
            get {
                return ResourceManager.GetString("NextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на НЕТ.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не снимать очки за неверный ответ.
        /// </summary>
        public static string NoPenaltyForWrongAnswer {
            get {
                return ResourceManager.GetString("NoPenaltyForWrongAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задан.
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опции.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устная игра.
        /// </summary>
        public static string OralGame {
            get {
                return ResourceManager.GetString("OralGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если ведущий – человек. Хорошо подходит для стримов. Игроки делают выбор и дают ответ голосом.
        /// </summary>
        public static string OralGame_Hint {
            get {
                return ResourceManager.GetString("OralGame_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прочее.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пакет.
        /// </summary>
        public static string Package {
            get {
                return ResourceManager.GetString("Package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Частичный текст вопросов.
        /// </summary>
        public static string PartialQuestions {
            get {
                return ResourceManager.GetString("PartialQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При игре без фальстартов текст выводится порционно.
        /// </summary>
        public static string PartialQuestions_Hint {
            get {
                return ResourceManager.GetString("PartialQuestions_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пас.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: ПАС на вопросе 1 категории.
        /// </summary>
        public static string PassOnQuestion1 {
            get {
                return ResourceManager.GetString("PassOnQuestion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: ПАС на вопросе 5 категории.
        /// </summary>
        public static string PassOnQuestion5 {
            get {
                return ResourceManager.GetString("PassOnQuestion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пауза.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string Person_Change {
            get {
                return ResourceManager.GetString("Person_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Person_Delete {
            get {
                return ResourceManager.GetString("Person_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на УЧАСТНИКИ.
        /// </summary>
        public static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игроки.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агрессивный.
        /// </summary>
        public static string PlayerStyle_Agressive {
            get {
                return ResourceManager.GetString("PlayerStyle_Agressive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осторожный.
        /// </summary>
        public static string PlayerStyle_Careful {
            get {
                return ResourceManager.GetString("PlayerStyle_Careful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Спокойный.
        /// </summary>
        public static string PlayerStyle_Normal {
            get {
                return ResourceManager.GetString("PlayerStyle_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма игрока:.
        /// </summary>
        public static string PlayerSum {
            get {
                return ResourceManager.GetString("PlayerSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер порта.
        /// </summary>
        public static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите клавишу.
        /// </summary>
        public static string PressTheButton {
            get {
                return ResourceManager.GetString("PressTheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущий раунд.
        /// </summary>
        public static string PreviousRound {
            get {
                return ResourceManager.GetString("PreviousRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профиль.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата публикации.
        /// </summary>
        public static string PublishedDate {
            get {
                return ResourceManager.GetString("PublishedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Издатель.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Библиотека вопросов….
        /// </summary>
        public static string QuestionLibrary {
            get {
                return ResourceManager.GetString("QuestionLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пакет вопросов.
        /// </summary>
        public static string QuestionPack {
            get {
                return ResourceManager.GetString("QuestionPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число раундов в случайном пакете.
        /// </summary>
        public static string RandomRoundsCount {
            get {
                return ResourceManager.GetString("RandomRoundsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случайный набор тем сервера.
        /// </summary>
        public static string RandomServer {
            get {
                return ResourceManager.GetString("RandomServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на случайные спецвопросы.
        /// </summary>
        public static string RandomSpecials {
            get {
                return ResourceManager.GetString("RandomSpecials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Случайный набор тем.
        /// </summary>
        public static string RandomThemes {
            get {
                return ResourceManager.GetString("RandomThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Число тем в случайном пакете.
        /// </summary>
        public static string RandomThemesCount {
            get {
                return ResourceManager.GetString("RandomThemesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость реакции.
        /// </summary>
        public static string ReactionSpeed {
            get {
                return ResourceManager.GetString("ReactionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость чтения вопроса.
        /// </summary>
        public static string ReadingSpeed {
            get {
                return ResourceManager.GetString("ReadingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Готов.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заменить на.
        /// </summary>
        public static string ReplaceTo {
            get {
                return ResourceManager.GetString("ReplaceTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчёт об игре содержит информацию об итогах игры, об апеллированных ответах и ваших неправильных версиях. Он позволяет сделать игру лучше.
        /// </summary>
        public static string Report_Info {
            get {
                return ResourceManager.GetString("Report_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось подключиться к серверу при отправке отчёта об ошибке. Отчёт будет отправлен позднее..
        /// </summary>
        public static string ReportDelayed {
            get {
                return ResourceManager.GetString("ReportDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваши впечатления от игры.
        /// </summary>
        public static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на (требуется перезапуск).
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение.
        /// </summary>
        public static string Restriction {
            get {
                return ResourceManager.GetString("Restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Результат.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верные ответы.
        /// </summary>
        public static string RightAnswers {
            get {
                return ResourceManager.GetString("RightAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роль.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила игры.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настроить игру голосом, фальстарты, частичный вывод вопросов и многое другое.
        /// </summary>
        public static string RulesHint {
            get {
                return ResourceManager.GetString("RulesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string RunUpdate {
            get {
                return ResourceManager.GetString("RunUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск обновлений.
        /// </summary>
        public static string SeacrhForUpdates {
            get {
                return ResourceManager.GetString("SeacrhForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите аватар.
        /// </summary>
        public static string SelectAvatar {
            get {
                return ResourceManager.GetString("SelectAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать….
        /// </summary>
        public static string SelectBackground {
            get {
                return ResourceManager.GetString("SelectBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите имя файла для экспорта.
        /// </summary>
        public static string SelectExportFileName {
            get {
                return ResourceManager.GetString("SelectExportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл логотипа игры.
        /// </summary>
        public static string SelectGameLogoFileName {
            get {
                return ResourceManager.GetString("SelectGameLogoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите игровой пакет.
        /// </summary>
        public static string SelectGamePackage {
            get {
                return ResourceManager.GetString("SelectGamePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите имя файла для импорта.
        /// </summary>
        public static string SelectImportFileName {
            get {
                return ResourceManager.GetString("SelectImportFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: вопрос дешевле, чем был.
        /// </summary>
        public static string Selection_CheapQuestion {
            get {
                return ResourceManager.GetString("Selection_CheapQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: вопрос дороже, чем был.
        /// </summary>
        public static string Selection_ExpensiveQuestion {
            get {
                return ResourceManager.GetString("Selection_ExpensiveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: тема останется той же, что и была.
        /// </summary>
        public static string Selection_KeepTheme {
            get {
                return ResourceManager.GetString("Selection_KeepTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор вопроса согласно номеру вопроса.
        /// </summary>
        public static string Selection_PreferQuestionNumber {
            get {
                return ResourceManager.GetString("Selection_PreferQuestionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: выбор вопроса согласно номеру темы, а не номеру вопроса.
        /// </summary>
        public static string Selection_PreferTheme {
            get {
                return ResourceManager.GetString("Selection_PreferTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор вопроса согласно номеру темы.
        /// </summary>
        public static string Selection_PreferThemeNumber {
            get {
                return ResourceManager.GetString("Selection_PreferThemeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приоритет вопросов.
        /// </summary>
        public static string Selection_QuestionPriority {
            get {
                return ResourceManager.GetString("Selection_QuestionPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: случайный вопрос.
        /// </summary>
        public static string Selection_RandomQuestion {
            get {
                return ResourceManager.GetString("Selection_RandomQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: случайная тема.
        /// </summary>
        public static string Selection_RandomTheme {
            get {
                return ResourceManager.GetString("Selection_RandomTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: вопрос той же цены.
        /// </summary>
        public static string Selection_SamePriceQuestion {
            get {
                return ResourceManager.GetString("Selection_SamePriceQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приоритет тем.
        /// </summary>
        public static string Selection_ThemePriority {
            get {
                return ResourceManager.GetString("Selection_ThemePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: вопрос согласно приоритету.
        /// </summary>
        public static string Selection_UseQuestionPriority {
            get {
                return ResourceManager.GetString("Selection_UseQuestionPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вероятность: тема согласно приоритету тем.
        /// </summary>
        public static string Selection_UseThemePriority {
            get {
                return ResourceManager.GetString("Selection_UseThemePriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор вопроса.
        /// </summary>
        public static string SelectionStyle {
            get {
                return ResourceManager.GetString("SelectionStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите новую папку для хранения логов.
        /// </summary>
        public static string SelectLogsFolder {
            get {
                return ResourceManager.GetString("SelectLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл для главного фонового изображения.
        /// </summary>
        public static string SelectMainBackgroundFIleName {
            get {
                return ResourceManager.GetString("SelectMainBackgroundFIleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите мелодию.
        /// </summary>
        public static string SelectSoundFile {
            get {
                return ResourceManager.GetString("SelectSoundFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите файл для фонового изображения студии.
        /// </summary>
        public static string SelectStudiaBackgroundFileName {
            get {
                return ResourceManager.GetString("SelectStudiaBackgroundFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправлять отчёт об игре.
        /// </summary>
        public static string SendGameReport {
            get {
                return ResourceManager.GetString("SendGameReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить отчёт.
        /// </summary>
        public static string SendReport {
            get {
                return ResourceManager.GetString("SendReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя сервера.
        /// </summary>
        public static string ServerName {
            get {
                return ResourceManager.GetString("ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По умолчанию.
        /// </summary>
        public static string Settings_Default {
            get {
                return ResourceManager.GetString("Settings_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспорт….
        /// </summary>
        public static string Settings_Export {
            get {
                return ResourceManager.GetString("Settings_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Импорт….
        /// </summary>
        public static string Settings_Import {
            get {
                return ResourceManager.GetString("Settings_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Управление настройками.
        /// </summary>
        public static string SettingsManagement {
            get {
                return ResourceManager.GetString("SettingsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол.
        /// </summary>
        public static string Sex {
            get {
                return ResourceManager.GetString("Sex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3D-анимации на табло.
        /// </summary>
        public static string ShowAnimations {
            get {
                return ResourceManager.GetString("ShowAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать рамку в начале чтения вопроса при игре без фальстартов.
        /// </summary>
        public static string ShowBorderOnFalseStart {
            get {
                return ResourceManager.GetString("ShowBorderOnFalseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать чат.
        /// </summary>
        public static string ShowChat {
            get {
                return ResourceManager.GetString("ShowChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ведущий.
        /// </summary>
        public static string Showman {
            get {
                return ResourceManager.GetString("Showman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробнее.
        /// </summary>
        public static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопросы SIGame.
        /// </summary>
        public static string SIQuestions {
            get {
                return ResourceManager.GetString("SIQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки SIGame.
        /// </summary>
        public static string SISettings {
            get {
                return ResourceManager.GetString("SISettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при переходе на сайт {0}. Убедитесь, что у вас настроен браузер по умолчанию..
        /// </summary>
        public static string SiteNavigationError {
            get {
                return ResourceManager.GetString("SiteNavigationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пропустить.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Звук.
        /// </summary>
        public static string Sound {
            get {
                return ResourceManager.GetString("Sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия начала раунда.
        /// </summary>
        public static string Sound_BeginRound {
            get {
                return ResourceManager.GetString("Sound_BeginRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия финального размышления.
        /// </summary>
        public static string Sound_FinalQuestion {
            get {
                return ResourceManager.GetString("Sound_FinalQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия главного меню.
        /// </summary>
        public static string Sound_MainMenu {
            get {
                return ResourceManager.GetString("Sound_MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия отсутствия ответов.
        /// </summary>
        public static string Sound_NoAnswer {
            get {
                return ResourceManager.GetString("Sound_NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия вопроса без риска.
        /// </summary>
        public static string Sound_NoRiskQuestion {
            get {
                return ResourceManager.GetString("Sound_NoRiskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия тем раунда.
        /// </summary>
        public static string Sound_RoundThemes {
            get {
                return ResourceManager.GetString("Sound_RoundThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия окончания времени раунда.
        /// </summary>
        public static string Sound_RoundTimeout {
            get {
                return ResourceManager.GetString("Sound_RoundTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия вопроса с секретом.
        /// </summary>
        public static string Sound_SecretQuestion {
            get {
                return ResourceManager.GetString("Sound_SecretQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодия вопроса со ставкой.
        /// </summary>
        public static string Sound_StakeQuestion {
            get {
                return ResourceManager.GetString("Sound_StakeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мелодии.
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ставка.
        /// </summary>
        public static string Stake {
            get {
                return ResourceManager.GetString("Stake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начата.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать игру.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень сложности: высокий.
        /// </summary>
        public static string Strength_High {
            get {
                return ResourceManager.GetString("Strength_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень сложности: низкий.
        /// </summary>
        public static string Strength_Low {
            get {
                return ResourceManager.GetString("Strength_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень сложности: средний.
        /// </summary>
        public static string Strength_Middle {
            get {
                return ResourceManager.GetString("Strength_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фоновое изображение студии.
        /// </summary>
        public static string StudiaBackground {
            get {
                return ResourceManager.GetString("StudiaBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действует для всех участников игры.
        /// </summary>
        public static string StudiaBackground_Hint {
            get {
                return ResourceManager.GetString("StudiaBackground_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение суммы.
        /// </summary>
        public static string SumChange {
            get {
                return ResourceManager.GetString("SumChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Суммы.
        /// </summary>
        public static string Sums {
            get {
                return ResourceManager.GetString("Sums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить суммы участников.
        /// </summary>
        public static string Sums_Hint {
            get {
                return ResourceManager.GetString("Sums_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чат.
        /// </summary>
        public static string Tab_Chat {
            get {
                return ResourceManager.GetString("Tab_Chat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игры.
        /// </summary>
        public static string Tab_Games {
            get {
                return ResourceManager.GetString("Tab_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игроки.
        /// </summary>
        public static string Tab_Players {
            get {
                return ResourceManager.GetString("Tab_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет фона табло.
        /// </summary>
        public static string TableBackground {
            get {
                return ResourceManager.GetString("TableBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цвет текста табло.
        /// </summary>
        public static string TableColor {
            get {
                return ResourceManager.GetString("TableColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шрифт табло.
        /// </summary>
        public static string TableFont {
            get {
                return ResourceManager.GetString("TableFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эти настройки задаются до входа в комнату игры.
        /// </summary>
        public static string TheseSettingsAreChangedBeforeGame {
            get {
                return ResourceManager.GetString("TheseSettingsAreChangedBeforeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время на принятие решения.
        /// </summary>
        public static string Time_Decide {
            get {
                return ResourceManager.GetString("Time_Decide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время на нажатие кнопки.
        /// </summary>
        public static string Time_Press {
            get {
                return ResourceManager.GetString("Time_Press", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время раунда.
        /// </summary>
        public static string Time_Round {
            get {
                return ResourceManager.GetString("Time_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки времени.
        /// </summary>
        public static string TimeSettings {
            get {
                return ResourceManager.GetString("TimeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транслировать игру в чат.
        /// </summary>
        public static string TranslateToChat {
            get {
                return ResourceManager.GetString("TranslateToChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Попробуйте переустановить программу.
        /// </summary>
        public static string TryReinstallApp {
            get {
                return ResourceManager.GetString("TryReinstallApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Интерфейс.
        /// </summary>
        public static string UI {
            get {
                return ResourceManager.GetString("UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновление.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При поиске обновления возникла следующая ошибка: {0}.
        /// </summary>
        public static string UpdateException {
            get {
                return ResourceManager.GetString("UpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользовательские пакеты….
        /// </summary>
        public static string UserPackages {
            get {
                return ResourceManager.GetString("UserPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верен ли ответ игрока.
        /// </summary>
        public static string Validate_IsTrue {
            get {
                return ResourceManager.GetString("Validate_IsTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зрители.
        /// </summary>
        public static string Viewers {
            get {
                return ResourceManager.GetString("Viewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регулятор громкости.
        /// </summary>
        public static string VolumeControl {
            get {
                return ResourceManager.GetString("VolumeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать в СИ Онлайн!.
        /// </summary>
        public static string WelcomeToSIOnline {
            get {
                return ResourceManager.GetString("WelcomeToSIOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на женщина.
        /// </summary>
        public static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вести логи.
        /// </summary>
        public static string WriteLogs {
            get {
                return ResourceManager.GetString("WriteLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверные ответы.
        /// </summary>
        public static string WrongAnswers {
            get {
                return ResourceManager.GetString("WrongAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на помощь.
        /// </summary>
        public static string XpsHelp {
            get {
                return ResourceManager.GetString("XpsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДА.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ваш ответ.
        /// </summary>
        public static string YourAnswer {
            get {
                return ResourceManager.GetString("YourAnswer", resourceCulture);
            }
        }
    }
}
