//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SImulator.ViewModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SImulator.ViewModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button press.
        /// </summary>
        public static string ButtonPressed {
            get {
                return ResourceManager.GetString("ButtonPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select question.
        /// </summary>
        public static string ChooseQuest {
            get {
                return ResourceManager.GetString("ChooseQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error: {0}.
        /// </summary>
        public static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting theme in the final round.
        /// </summary>
        public static string FinalThemeRemoval {
            get {
                return ResourceManager.GetString("FinalThemeRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final round thinking.
        /// </summary>
        public static string FinalThink {
            get {
                return ResourceManager.GetString("FinalThink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game end error: {0}.
        /// </summary>
        public static string GameEndingError {
            get {
                return ResourceManager.GetString("GameEndingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection to the demonstration computer has been terminated. The game is stopped..
        /// </summary>
        public static string GameEndsBecauseOfConnectionLoss {
            get {
                return ResourceManager.GetString("GameEndsBecauseOfConnectionLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading game package.
        /// </summary>
        public static string GamePackageLoadError {
            get {
                return ResourceManager.GetString("GamePackageLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game start.
        /// </summary>
        public static string GameStart {
            get {
                return ResourceManager.GetString("GameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game start error: {0}.
        /// </summary>
        public static string GameStartError {
            get {
                return ResourceManager.GetString("GameStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game themes.
        /// </summary>
        public static string GameThemes {
            get {
                return ResourceManager.GetString("GameThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Your IP address].
        /// </summary>
        public static string IpAddressHint {
            get {
                return ResourceManager.GetString("IpAddressHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log file creation error: {0}. Logging will not be performed..
        /// </summary>
        public static string LoggerCreationWarning {
            get {
                return ResourceManager.GetString("LoggerCreationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error starting log recording.
        /// </summary>
        public static string LoggerInitError {
            get {
                return ResourceManager.GetString("LoggerInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log directory is not specified. Logs will not be recorded..
        /// </summary>
        public static string LogsFolderNotSetWarning {
            get {
                return ResourceManager.GetString("LogsFolderNotSetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No answer.
        /// </summary>
        public static string NoAnswer {
            get {
                return ResourceManager.GetString("NoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License folder not found.
        /// </summary>
        public static string NoLicensesFolder {
            get {
                return ResourceManager.GetString("NoLicensesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question for yourself.
        /// </summary>
        public static string NoRiskQuestion {
            get {
                return ResourceManager.GetString("NoRiskQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening license folder: {0}.
        /// </summary>
        public static string OpenLicensesError {
            get {
                return ResourceManager.GetString("OpenLicensesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package authors.
        /// </summary>
        public static string PackageAuthors {
            get {
                return ResourceManager.GetString("PackageAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package comments.
        /// </summary>
        public static string PackageComments {
            get {
                return ResourceManager.GetString("PackageComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package preparation error.
        /// </summary>
        public static string PackagePreparationError {
            get {
                return ResourceManager.GetString("PackagePreparationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button.
        /// </summary>
        public static string PressTheButton {
            get {
                return ResourceManager.GetString("PressTheButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1} with step {2}.
        /// </summary>
        public static string PriceFromToStep {
            get {
                return ResourceManager.GetString("PriceFromToStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum or maximum in the round.
        /// </summary>
        public static string PriceMinMaxRound {
            get {
                return ResourceManager.GetString("PriceMinMaxRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1}.
        /// </summary>
        public static string PriceOr {
            get {
                return ResourceManager.GetString("PriceOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question selection.
        /// </summary>
        public static string QuestionSelection {
            get {
                return ResourceManager.GetString("QuestionSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question For All.
        /// </summary>
        public static string QuestionTypeForAll {
            get {
                return ResourceManager.GetString("QuestionTypeForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question with Secret.
        /// </summary>
        public static string QuestionTypeSecret {
            get {
                return ResourceManager.GetString("QuestionTypeSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question with Button.
        /// </summary>
        public static string QuestionTypeSimple {
            get {
                return ResourceManager.GetString("QuestionTypeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question with Stake.
        /// </summary>
        public static string QuestionTypeStake {
            get {
                return ResourceManager.GetString("QuestionTypeStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question For All with Stake.
        /// </summary>
        public static string QuestionTypeStakeForAll {
            get {
                return ResourceManager.GetString("QuestionTypeStakeForAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer.
        /// </summary>
        public static string RightAnswer {
            get {
                return ResourceManager.GetString("RightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round start.
        /// </summary>
        public static string RoundStart {
            get {
                return ResourceManager.GetString("RoundStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round themes.
        /// </summary>
        public static string RoundThemes {
            get {
                return ResourceManager.GetString("RoundThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round time has expired..
        /// </summary>
        public static string RoundTimeout {
            get {
                return ResourceManager.GetString("RoundTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret question.
        /// </summary>
        public static string SecretQuestion {
            get {
                return ResourceManager.GetString("SecretQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone.
        /// </summary>
        public static string SelectAny {
            get {
                return ResourceManager.GetString("SelectAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone except yourself.
        /// </summary>
        public static string SelectAnyExceptCurrent {
            get {
                return ResourceManager.GetString("SelectAnyExceptCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select audio file.
        /// </summary>
        public static string SelectAudioFile {
            get {
                return ResourceManager.GetString("SelectAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select background image.
        /// </summary>
        public static string SelectBackgroundImage {
            get {
                return ResourceManager.GetString("SelectBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select background video file.
        /// </summary>
        public static string SelectBackgroundVideo {
            get {
                return ResourceManager.GetString("SelectBackgroundVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select splash video file.
        /// </summary>
        public static string SelectIntroVideo {
            get {
                return ResourceManager.GetString("SelectIntroVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be given to.
        /// </summary>
        public static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select splash image.
        /// </summary>
        public static string SelectLogoImage {
            get {
                return ResourceManager.GetString("SelectLogoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake question.
        /// </summary>
        public static string StakeQuestion {
            get {
                return ResourceManager.GetString("StakeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong answer.
        /// </summary>
        public static string WrongAnswer {
            get {
                return ResourceManager.GetString("WrongAnswer", resourceCulture);
            }
        }
    }
}
