//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SI.GameServer.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SI.GameServer.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot determine server address!.
        /// </summary>
        public static string CannotGetServerAddress {
            get {
                return ResourceManager.GetString("CannotGetServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server list is empty.
        /// </summary>
        public static string EmptyServerList {
            get {
                return ResourceManager.GetString("EmptyServerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Empty server uri.
        /// </summary>
        public static string EmptyServerUri {
            get {
                return ResourceManager.GetString("EmptyServerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file it too large.
        /// </summary>
        public static string FileTooLarge {
            get {
                return ResourceManager.GetString("FileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ignore wrong.
        /// </summary>
        public static string GameRule_IgnoreWrong {
            get {
                return ResourceManager.GetString("GameRule_IgnoreWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на no falstarts.
        /// </summary>
        public static string GameRule_NoFalseStart {
            get {
                return ResourceManager.GetString("GameRule_NoFalseStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на oral.
        /// </summary>
        public static string GameRule_Oral {
            get {
                return ResourceManager.GetString("GameRule_Oral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на simplified.
        /// </summary>
        public static string GameRule_Sport {
            get {
                return ResourceManager.GetString("GameRule_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Created.
        /// </summary>
        public static string GameStage_Created {
            get {
                return ResourceManager.GetString("GameStage_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Final.
        /// </summary>
        public static string GameStage_Final {
            get {
                return ResourceManager.GetString("GameStage_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finished.
        /// </summary>
        public static string GameStage_Finished {
            get {
                return ResourceManager.GetString("GameStage_Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Round.
        /// </summary>
        public static string GameStage_Round {
            get {
                return ResourceManager.GetString("GameStage_Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Started.
        /// </summary>
        public static string GameStage_Started {
            get {
                return ResourceManager.GetString("GameStage_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This login is forbidden on the server.
        /// </summary>
        public static string LoginForbidden {
            get {
                return ResourceManager.GetString("LoginForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your game version is obsolete. You need to upgrade it.
        /// </summary>
        public static string ObsoleClient {
            get {
                return ResourceManager.GetString("ObsoleClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A user with such name is already on the server.
        /// </summary>
        public static string OnlineUserConflict {
            get {
                return ResourceManager.GetString("OnlineUserConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Package upload failed. Maybe your package is too large. Or try later.
        /// </summary>
        public static string UploadPackageConnectionError {
            get {
                return ResourceManager.GetString("UploadPackageConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The pack sending time is expired. Please, try again, or reduce the size of the file.
        /// </summary>
        public static string UploadPackageTimeout {
            get {
                return ResourceManager.GetString("UploadPackageTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your were kicked from the game.
        /// </summary>
        public static string YourWereKicked {
            get {
                return ResourceManager.GetString("YourWereKicked", resourceCulture);
            }
        }
    }
}
