//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SImulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SImulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add player.
        /// </summary>
        public static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address to connect.
        /// </summary>
        public static string AddressToConnect {
            get {
                return ResourceManager.GetString("AddressToConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add sum.
        /// </summary>
        public static string AddSum {
            get {
                return ResourceManager.GetString("AddSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to active player.
        /// </summary>
        public static string AddSumForActivePlayer {
            get {
                return ResourceManager.GetString("AddSumForActivePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alias.
        /// </summary>
        public static string Alias {
            get {
                return ResourceManager.GetString("Alias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all).
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color for the answering player.
        /// </summary>
        public static string AnswererBackgroundColor {
            get {
                return ResourceManager.GetString("AnswererBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer options.
        /// </summary>
        public static string AnswerOptions {
            get {
                return ResourceManager.GetString("AnswerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application language (requires restart).
        /// </summary>
        public static string AppLanguage {
            get {
                return ResourceManager.GetString("AppLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SImulator.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add theme comments and right answers to game table.
        /// </summary>
        public static string AttachContentToTable {
            get {
                return ResourceManager.GetString("AttachContentToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vladimir Khil.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic game management (without a host).
        /// </summary>
        public static string AutomaticGame {
            get {
                return ResourceManager.GetString("AutomaticGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background video file.
        /// </summary>
        public static string BackgroundVideo {
            get {
                return ResourceManager.GetString("BackgroundVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button lock time (s).
        /// </summary>
        public static string ButtonBlockingTime {
            get {
                return ResourceManager.GetString("ButtonBlockingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches positions of players in the list.
        /// </summary>
        public static string ButtonOrderHint {
            get {
                return ResourceManager.GetString("ButtonOrderHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons.
        /// </summary>
        public static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port.
        /// </summary>
        public static string ButtonTypesCom {
            get {
                return ResourceManager.GetString("ButtonTypesCom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External.
        /// </summary>
        public static string ButtonTypesExternal {
            get {
                return ResourceManager.GetString("ButtonTypesExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick.
        /// </summary>
        public static string ButtonTypesJoystick {
            get {
                return ResourceManager.GetString("ButtonTypesJoystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string ButtonTypesKeyboard {
            get {
                return ResourceManager.GetString("ButtonTypesKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use.
        /// </summary>
        public static string ButtonTypesNone {
            get {
                return ResourceManager.GetString("ButtonTypesNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web access.
        /// </summary>
        public static string ButtonTypesWeb {
            get {
                return ResourceManager.GetString("ButtonTypesWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string ByDefault {
            get {
                return ResourceManager.GetString("ByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to characters per second.
        /// </summary>
        public static string CharactersPerSecond {
            get {
                return ResourceManager.GetString("CharactersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a player to answer.
        /// </summary>
        public static string ChoosePlayerToAnswer {
            get {
                return ResourceManager.GetString("ChoosePlayerToAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a player to start the game.
        /// </summary>
        public static string ChoosePlayerToStart {
            get {
                return ResourceManager.GetString("ChoosePlayerToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear list.
        /// </summary>
        public static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the application: {0}\r\n\r\nThe application will be closed. Please contact the developer..
        /// </summary>
        public static string CommonAppError {
            get {
                return ResourceManager.GetString("CommonAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses of used components.
        /// </summary>
        public static string ComponentsLicenses {
            get {
                return ResourceManager.GetString("ComponentsLicenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port number.
        /// </summary>
        public static string ComPortNumber {
            get {
                return ResourceManager.GetString("ComPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (by default).
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk space is running out.
        /// </summary>
        public static string DiskFullError {
            get {
                return ResourceManager.GetString("DiskFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback statistics when stepping back.
        /// </summary>
        public static string DropStatsOnBack {
            get {
                return ResourceManager.GetString("DropStatsOnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear players sums and counters of their correct and incorrect answers.
        /// </summary>
        public static string DropStatsOnBackHint {
            get {
                return ResourceManager.GetString("DropStatsOnBackHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End the question on correct answer.
        /// </summary>
        public static string EndQuestionOnRightAnswer {
            get {
                return ResourceManager.GetString("EndQuestionOnRightAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This error is not reproducible. If you can reliably reproduce it, please contact the author..
        /// </summary>
        public static string ErrorCannotReproduce {
            get {
                return ResourceManager.GetString("ErrorCannotReproduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to connect to the server when sending the error report. The report will be sent later..
        /// </summary>
        public static string ErrorConnectionError {
            get {
                return ResourceManager.GetString("ErrorConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This error has been fixed in the new version of the program. Please update..
        /// </summary>
        public static string ErrorFixed {
            get {
                return ResourceManager.GetString("ErrorFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred in the application: {0}
        ///The application will be closed. Send information to the developer?.
        /// </summary>
        public static string ErrorSendConfirm {
            get {
                return ResourceManager.GetString("ErrorSendConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this mode, buttons not connected to the program (independent devices, claps, etc.) are used. The program displays a frame when it is possible to press (during the game with false starts)..
        /// </summary>
        public static string ExternalButtonsHint {
            get {
                return ResourceManager.GetString("ExternalButtonsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game with false starts.
        /// </summary>
        public static string FalseStartGame {
            get {
                return ResourceManager.GetString("FalseStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When playing with false starts:
        ///question text is displayed on the screen;
        ///when using buttons to start the question timer, an additional press of the Next button is required, and a colored frame lights up on the screen&quot;.
        /// </summary>
        public static string FalseStartGameHint {
            get {
                return ResourceManager.GetString("FalseStartGameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia with false starts.
        /// </summary>
        public static string FalseStartMultimedia {
            get {
                return ResourceManager.GetString("FalseStartMultimedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents pressing the button during multimedia file playback.
        /// </summary>
        public static string FalseStartMultimediaHint {
            get {
                return ResourceManager.GetString("FalseStartMultimediaHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting file: {0}.
        /// </summary>
        public static string FileDeletionError {
            get {
                return ResourceManager.GetString("FileDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final round thinking time (s).
        /// </summary>
        public static string FinalThinkingTime {
            get {
                return ResourceManager.GetString("FinalThinkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish game?.
        /// </summary>
        public static string FinishGameQuestion {
            get {
                return ResourceManager.GetString("FinishGameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game buttons.
        /// </summary>
        public static string GameButtons {
            get {
                return ResourceManager.GetString("GameButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simplified.
        /// </summary>
        public static string GameModes_Sport {
            get {
                return ResourceManager.GetString("GameModes_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic.
        /// </summary>
        public static string GameModes_Tv {
            get {
                return ResourceManager.GetString("GameModes_Tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game package.
        /// </summary>
        public static string GamePackage {
            get {
                return ResourceManager.GetString("GamePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game rules.
        /// </summary>
        public static string GameRules {
            get {
                return ResourceManager.GetString("GameRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game type.
        /// </summary>
        public static string GameType {
            get {
                return ResourceManager.GetString("GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass the turn.
        /// </summary>
        public static string GiveTurn {
            get {
                return ResourceManager.GetString("GiveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid color.
        /// </summary>
        public static string GridColor {
            get {
                return ResourceManager.GetString("GridColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the &quot;Next&quot; button to control the game progress.
        /// </summary>
        public static string HintBeforeStart {
            get {
                return ResourceManager.GetString("HintBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Game themes).
        /// </summary>
        public static string HintGameThemes {
            get {
                return ResourceManager.GetString("HintGameThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Splash screen).
        /// </summary>
        public static string HintIntro {
            get {
                return ResourceManager.GetString("HintIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        public static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splash video file.
        /// </summary>
        public static string IntroVideo {
            get {
                return ResourceManager.GetString("IntroVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick not found.
        /// </summary>
        public static string JoystickNotFound {
            get {
                return ResourceManager.GetString("JoystickNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error completing keyboard listening.
        /// </summary>
        public static string KeyboardDetachError {
            get {
                return ResourceManager.GetString("KeyboardDetachError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error listening to the keyboard.
        /// </summary>
        public static string KeyboardListeningError {
            get {
                return ResourceManager.GetString("KeyboardListeningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick player.
        /// </summary>
        public static string KickPlayer {
            get {
                return ResourceManager.GetString("KickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All exclusive copyrights to the Software Product and its documentation in print and/or electronic form belong to the Author.
        ///
        ///The program is distributed free of charge.
        ///
        ///The User has the right to freely use and distribute this Program, place it on websites, and carry out other activities not prohibited by the legislation of their country of operation with it for any period of time, provided that the copyrights are preserved.
        ///
        ///The program is provided &quot;as is&quot;. The Author does not provide any guarantees  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder for logging &quot;{0}&quot; was not found..
        /// </summary>
        public static string LogsFolderNotFound {
            get {
                return ResourceManager.GetString("LogsFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainScreen {
            get {
                return ResourceManager.GetString("MainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make stake.
        /// </summary>
        public static string MakeStake {
            get {
                return ResourceManager.GetString("MakeStake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while navigating to the program website ({0}). Make sure you have your default browser configured: {1}.
        /// </summary>
        public static string NavigateToSiteError {
            get {
                return ResourceManager.GetString("NavigateToSiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next round.
        /// </summary>
        public static string NextRound {
            get {
                return ResourceManager.GetString("NextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string NotSet {
            get {
                return ResourceManager.GetString("NotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old version.
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral.
        /// </summary>
        public static string Oral {
            get {
                return ResourceManager.GetString("Oral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral text.
        /// </summary>
        public static string OralText {
            get {
                return ResourceManager.GetString("OralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text is read by host and is not displayed on the screen.
        /// </summary>
        public static string OralTextHint {
            get {
                return ResourceManager.GetString("OralTextHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough memory to run the program.
        /// </summary>
        public static string OutOfMemoryError {
            get {
                return ResourceManager.GetString("OutOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string PlacementBackground {
            get {
                return ResourceManager.GetString("PlacementBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replica.
        /// </summary>
        public static string PlacementOral {
            get {
                return ResourceManager.GetString("PlacementOral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play content.
        /// </summary>
        public static string PlayContent {
            get {
                return ResourceManager.GetString("PlayContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player table.
        /// </summary>
        public static string PlayersTable {
            get {
                return ResourceManager.GetString("PlayersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sounds.
        /// </summary>
        public static string PlaySounds {
            get {
                return ResourceManager.GetString("PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play special questions.
        /// </summary>
        public static string PlaySpecials {
            get {
                return ResourceManager.GetString("PlaySpecials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To exit, press Escape, right mouse button, or tap slightly with your finger.
        /// </summary>
        public static string PresentationExitHint {
            get {
                return ResourceManager.GetString("PresentationExitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game table.
        /// </summary>
        public static string PresentationTitle {
            get {
                return ResourceManager.GetString("PresentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button.
        /// </summary>
        public static string PressButton {
            get {
                return ResourceManager.GetString("PressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image.
        /// </summary>
        public static string PreviewImage {
            get {
                return ResourceManager.GetString("PreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous round.
        /// </summary>
        public static string PreviousRound {
            get {
                return ResourceManager.GetString("PreviousRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1} with step {2}.
        /// </summary>
        public static string PriceFromToStep {
            get {
                return ResourceManager.GetString("PriceFromToStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum or maximum in the round.
        /// </summary>
        public static string PriceMinMaxRound {
            get {
                return ResourceManager.GetString("PriceMinMaxRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} or {1}.
        /// </summary>
        public static string PriceOr {
            get {
                return ResourceManager.GetString("PriceOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question library.
        /// </summary>
        public static string QuestionLibrary {
            get {
                return ResourceManager.GetString("QuestionLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line spacing in question.
        /// </summary>
        public static string QuestionLineSpacing {
            get {
                return ResourceManager.GetString("QuestionLineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question price.
        /// </summary>
        public static string QuestionPrice {
            get {
                return ResourceManager.GetString("QuestionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question reading speed.
        /// </summary>
        public static string QuestionReadingSpeed {
            get {
                return ResourceManager.GetString("QuestionReadingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button press time (s).
        /// </summary>
        public static string QuestionTime {
            get {
                return ResourceManager.GetString("QuestionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret question (money without question).
        /// </summary>
        public static string QuestionTypeSecretNoQuestion {
            get {
                return ResourceManager.GetString("QuestionTypeSecretNoQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secret question (theme and price known before passing the question).
        /// </summary>
        public static string QuestionTypeSecretPublicPrice {
            get {
                return ResourceManager.GetString("QuestionTypeSecretPublicPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        public static string QuestionTypeSimple {
            get {
                return ResourceManager.GetString("QuestionTypeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent files.
        /// </summary>
        public static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete player.
        /// </summary>
        public static string RemovePlayer {
            get {
                return ResourceManager.GetString("RemovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete sums and statistics.
        /// </summary>
        public static string ResetSums {
            get {
                return ResourceManager.GetString("ResetSums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restriction.
        /// </summary>
        public static string Restriction {
            get {
                return ResourceManager.GetString("Restriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string RightAnswers {
            get {
                return ResourceManager.GetString("RightAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round time (s).
        /// </summary>
        public static string RoundTime {
            get {
                return ResourceManager.GetString("RoundTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round timeout.
        /// </summary>
        public static string RoundTimeout {
            get {
                return ResourceManager.GetString("RoundTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create the main window of the program. It seems that the runtime environment of the program on your computer is corrupted: {0}.
        /// </summary>
        public static string RuntimeBrokenError {
            get {
                return ResourceManager.GetString("RuntimeBrokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save logs to folder.
        /// </summary>
        public static string SaveLogsToFolder {
            get {
                return ResourceManager.GetString("SaveLogsToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving program settings.
        /// </summary>
        public static string SavingSettingsError {
            get {
                return ResourceManager.GetString("SavingSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen.
        /// </summary>
        public static string Screen {
            get {
                return ResourceManager.GetString("Screen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional.
        /// </summary>
        public static string SecondaryScreen {
            get {
                return ResourceManager.GetString("SecondaryScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone.
        /// </summary>
        public static string SelectAny {
            get {
                return ResourceManager.GetString("SelectAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone except yourself.
        /// </summary>
        public static string SelectAnyExceptCurrent {
            get {
                return ResourceManager.GetString("SelectAnyExceptCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File….
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select….
        /// </summary>
        public static string SelectHeader {
            get {
                return ResourceManager.GetString("SelectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be given to.
        /// </summary>
        public static string SelectionMode {
            get {
                return ResourceManager.GetString("SelectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question library….
        /// </summary>
        public static string SelectLibrary {
            get {
                return ResourceManager.GetString("SelectLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder to save logs.
        /// </summary>
        public static string SelectLogsFolder {
            get {
                return ResourceManager.GetString("SelectLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Package.
        /// </summary>
        public static string SelectPackage {
            get {
                return ResourceManager.GetString("SelectPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select question package.
        /// </summary>
        public static string SelectQuestionPackage {
            get {
                return ResourceManager.GetString("SelectQuestionPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In separate window.
        /// </summary>
        public static string SeparateWindow {
            get {
                return ResourceManager.GetString("SeparateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign a button.
        /// </summary>
        public static string SetButton {
            get {
                return ResourceManager.GetString("SetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show players who lost the button.
        /// </summary>
        public static string ShowLostButtonPlayers {
            get {
                return ResourceManager.GetString("ShowLostButtonPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show player list.
        /// </summary>
        public static string ShowPlayersList {
            get {
                return ResourceManager.GetString("ShowPlayersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show QR code.
        /// </summary>
        public static string ShowQRCode {
            get {
                return ResourceManager.GetString("ShowQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show frame when the button can be pressed.
        /// </summary>
        public static string ShowQuestionBorder {
            get {
                return ResourceManager.GetString("ShowQuestionBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show correct answers.
        /// </summary>
        public static string ShowRightAnswers {
            get {
                return ResourceManager.GetString("ShowRightAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show title on the game scoreboard.
        /// </summary>
        public static string ShowTableCaption {
            get {
                return ResourceManager.GetString("ShowTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show text of questions during game without false starts.
        /// </summary>
        public static string ShowTextNoFalseStartsHint {
            get {
                return ResourceManager.GetString("ShowTextNoFalseStartsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept player signals after thinking time expires.
        /// </summary>
        public static string SignalsAfterTimerHint {
            get {
                return ResourceManager.GetString("SignalsAfterTimerHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI questions.
        /// </summary>
        public static string SIQuestions {
            get {
                return ResourceManager.GetString("SIQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error working with question library: {0}.
        /// </summary>
        public static string SIStorageError {
            get {
                return ResourceManager.GetString("SIStorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special questions aliases.
        /// </summary>
        public static string SpecialQuestionsAliases {
            get {
                return ResourceManager.GetString("SpecialQuestionsAliases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking time for special question (s).
        /// </summary>
        public static string SpecialThinkingTime {
            get {
                return ResourceManager.GetString("SpecialThinkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stake.
        /// </summary>
        public static string Stake {
            get {
                return ResourceManager.GetString("Stake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End game.
        /// </summary>
        public static string StopGame {
            get {
                return ResourceManager.GetString("StopGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduct points for wrong answer.
        /// </summary>
        public static string SubstractOnWrong {
            get {
                return ResourceManager.GetString("SubstractOnWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        public static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract amount.
        /// </summary>
        public static string SubtractSum {
            get {
                return ResourceManager.GetString("SubtractSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from active player.
        /// </summary>
        public static string SubtractSumForActivePlayer {
            get {
                return ResourceManager.GetString("SubtractSumForActivePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game table hotkeys:
        ///Space (left mouse button) - proceed
        ///Backspace - go back
        ///Escape (right mouse button) - end game.
        /// </summary>
        public static string TableHotKeysHint {
            get {
                return ResourceManager.GetString("TableHotKeysHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test package.
        /// </summary>
        public static string TestPackage {
            get {
                return ResourceManager.GetString("TestPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text color.
        /// </summary>
        public static string TextColor {
            get {
                return ResourceManager.GetString("TextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme comments.
        /// </summary>
        public static string ThemeComments {
            get {
                return ResourceManager.GetString("ThemeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking.
        /// </summary>
        public static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thinking time after button press (s).
        /// </summary>
        public static string ThinkingTime {
            get {
                return ResourceManager.GetString("ThinkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type.
        /// </summary>
        public static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use keyboard selection on scoreboard.
        /// </summary>
        public static string UseKeysToSelectQuestions {
            get {
                return ResourceManager.GetString("UseKeysToSelectQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows selecting questions on the scoreboard using two consecutive presses of the number buttons (theme number, question number/Escape to cancel) and removing themes in the final round with one press.
        /// </summary>
        public static string UseKeysToSelectQuestionsHint {
            get {
                return ResourceManager.GetString("UseKeysToSelectQuestionsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SIGame engine.
        /// </summary>
        public static string UseSIGameEngine {
            get {
                return ResourceManager.GetString("UseSIGameEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection address for game: http://.
        /// </summary>
        public static string WebButtonsConnectionString {
            get {
                return ResourceManager.GetString("WebButtonsConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this mode, mobile devices of participants (phones, tablets, etc.) are used as buttons. Before the game starts, these devices are registered and associated with players.
        ///To play, you need to organize a local network..
        /// </summary>
        public static string WebButtonsHint {
            get {
                return ResourceManager.GetString("WebButtonsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web access port.
        /// </summary>
        public static string WebButtonsPort {
            get {
                return ResourceManager.GetString("WebButtonsPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string WebView {
            get {
                return ResourceManager.GetString("WebView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window (old version).
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string WrongAnswers {
            get {
                return ResourceManager.GetString("WrongAnswers", resourceCulture);
            }
        }
    }
}
