//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SImulator.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SImulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить игрока.
        /// </summary>
        public static string AddPlayer {
            get {
                return ResourceManager.GetString("AddPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить сумму.
        /// </summary>
        public static string AddSum {
            get {
                return ResourceManager.GetString("AddSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить активному игроку.
        /// </summary>
        public static string AddSumForActivePlayer {
            get {
                return ResourceManager.GetString("AddSumForActivePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Варианты ответа.
        /// </summary>
        public static string AnswerOptions {
            get {
                return ResourceManager.GetString("AnswerOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аудио.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение-фон.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видеофайл-фон.
        /// </summary>
        public static string BackgroundVideo {
            get {
                return ResourceManager.GetString("BackgroundVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По умолчанию.
        /// </summary>
        public static string ByDefault {
            get {
                return ResourceManager.GetString("ByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите игрока для ответа.
        /// </summary>
        public static string ChoosePlayerToAnswer {
            get {
                return ResourceManager.GetString("ChoosePlayerToAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите игрока, начинающего игру.
        /// </summary>
        public static string ChoosePlayerToStart {
            get {
                return ResourceManager.GetString("ChoosePlayerToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Очистить список.
        /// </summary>
        public static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка в приложении: {0}\r\n\r\nПриложение будет закрыто. Обратитесь к разработчику..
        /// </summary>
        public static string CommonAppError {
            get {
                return ResourceManager.GetString("CommonAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внешний вид.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закончилось место на диске!.
        /// </summary>
        public static string DiskFullError {
            get {
                return ResourceManager.GetString("DiskFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка удаления файла: {0}.
        /// </summary>
        public static string FileDeletionError {
            get {
                return ResourceManager.GetString("FileDeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время на размышление в финале (с).
        /// </summary>
        public static string FinalThinkingTime {
            get {
                return ResourceManager.GetString("FinalThinkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить игру?.
        /// </summary>
        public static string FinishGameQuestion {
            get {
                return ResourceManager.GetString("FinishGameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игра.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Упрощённая.
        /// </summary>
        public static string GameModes_Sport {
            get {
                return ResourceManager.GetString("GameModes_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классическая.
        /// </summary>
        public static string GameModes_Tv {
            get {
                return ResourceManager.GetString("GameModes_Tv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игровой пакет.
        /// </summary>
        public static string GamePackage {
            get {
                return ResourceManager.GetString("GamePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правила игры.
        /// </summary>
        public static string GameRules {
            get {
                return ResourceManager.GetString("GameRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип игры.
        /// </summary>
        public static string GameType {
            get {
                return ResourceManager.GetString("GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Передать ход.
        /// </summary>
        public static string GiveTurn {
            get {
                return ResourceManager.GetString("GiveTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HTML.
        /// </summary>
        public static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заставочный видеофайл.
        /// </summary>
        public static string IntroVideo {
            get {
                return ResourceManager.GetString("IntroVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка завершения прослушивания клавиатуры.
        /// </summary>
        public static string KeyboardDetachError {
            get {
                return ResourceManager.GetString("KeyboardDetachError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка прослушивания клавиатуры.
        /// </summary>
        public static string KeyboardListeningError {
            get {
                return ResourceManager.GetString("KeyboardListeningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Папка для записи логов &quot;{0}&quot; не найдена.
        /// </summary>
        public static string LogsFolderNotFound {
            get {
                return ResourceManager.GetString("LogsFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основной.
        /// </summary>
        public static string MainScreen {
            get {
                return ResourceManager.GetString("MainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при переходе на сайт программы ({0}). Убедитесь, что у вас настроен браузер по умолчанию: {1}.
        /// </summary>
        public static string NavigateToSiteError {
            get {
                return ResourceManager.GetString("NavigateToSiteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дальше.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Устный текст.
        /// </summary>
        public static string Oral {
            get {
                return ResourceManager.GetString("Oral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недостаточно памяти для выполнения программы!.
        /// </summary>
        public static string OutOfMemoryError {
            get {
                return ResourceManager.GetString("OutOfMemoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пас.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фон.
        /// </summary>
        public static string PlacementBackground {
            get {
                return ResourceManager.GetString("PlacementBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Реплика.
        /// </summary>
        public static string PlacementOral {
            get {
                return ResourceManager.GetString("PlacementOral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игроки.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таблица игроков.
        /// </summary>
        public static string PlayersTable {
            get {
                return ResourceManager.GetString("PlayersTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Играть звуки.
        /// </summary>
        public static string PlaySounds {
            get {
                return ResourceManager.GetString("PlaySounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для выхода нажмите Escape, правую кнопку мыши или немного надавите пальцем.
        /// </summary>
        public static string PresentationExitHint {
            get {
                return ResourceManager.GetString("PresentationExitHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Игровое табло.
        /// </summary>
        public static string PresentationTitle {
            get {
                return ResourceManager.GetString("PresentationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нажмите кнопку.
        /// </summary>
        public static string PressButton {
            get {
                return ResourceManager.GetString("PressButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение-заставка.
        /// </summary>
        public static string PreviewImage {
            get {
                return ResourceManager.GetString("PreviewImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предыдущий раунд.
        /// </summary>
        public static string PreviousRound {
            get {
                return ResourceManager.GetString("PreviousRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От {0} до {1} с шагом {2}.
        /// </summary>
        public static string PriceFromToStep {
            get {
                return ResourceManager.GetString("PriceFromToStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Минимум или максимум в раунде.
        /// </summary>
        public static string PriceMinMaxRound {
            get {
                return ResourceManager.GetString("PriceMinMaxRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} или {1}.
        /// </summary>
        public static string PriceOr {
            get {
                return ResourceManager.GetString("PriceOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Межстрочный интервал в вопросе.
        /// </summary>
        public static string QuestionLineSpacing {
            get {
                return ResourceManager.GetString("QuestionLineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время вопроса (c).
        /// </summary>
        public static string QuestionTime {
            get {
                return ResourceManager.GetString("QuestionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последние файлы.
        /// </summary>
        public static string RecentFiles {
            get {
                return ResourceManager.GetString("RecentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить игрока.
        /// </summary>
        public static string RemovePlayer {
            get {
                return ResourceManager.GetString("RemovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить суммы и статистику.
        /// </summary>
        public static string ResetSums {
            get {
                return ResourceManager.GetString("ResetSums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Верных.
        /// </summary>
        public static string RightAnswers {
            get {
                return ResourceManager.GetString("RightAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Раунд.
        /// </summary>
        public static string Round {
            get {
                return ResourceManager.GetString("Round", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время раунда (с).
        /// </summary>
        public static string RoundTime {
            get {
                return ResourceManager.GetString("RoundTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось создать главное окно программы! Похоже, на вашем компьютере повреждена среда выполнения программ: {0}.
        /// </summary>
        public static string RuntimeBrokenError {
            get {
                return ResourceManager.GetString("RuntimeBrokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при сохранении настроек программы.
        /// </summary>
        public static string SavingSettingsError {
            get {
                return ResourceManager.GetString("SavingSettingsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительный.
        /// </summary>
        public static string SecondaryScreen {
            get {
                return ResourceManager.GetString("SecondaryScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кому угодно.
        /// </summary>
        public static string SelectAny {
            get {
                return ResourceManager.GetString("SelectAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кому угодно, кроме себя.
        /// </summary>
        public static string SelectAnyExceptCurrent {
            get {
                return ResourceManager.GetString("SelectAnyExceptCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл….
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать….
        /// </summary>
        public static string SelectHeader {
            get {
                return ResourceManager.GetString("SelectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Библиотека вопросов….
        /// </summary>
        public static string SelectLibrary {
            get {
                return ResourceManager.GetString("SelectLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите папку для записи логов.
        /// </summary>
        public static string SelectLogsFolder {
            get {
                return ResourceManager.GetString("SelectLogsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите пакет вопросов.
        /// </summary>
        public static string SelectQuestionPackage {
            get {
                return ResourceManager.GetString("SelectQuestionPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задать кнопку.
        /// </summary>
        public static string SetButton {
            get {
                return ResourceManager.GetString("SetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать список игроков.
        /// </summary>
        public static string ShowPlayersList {
            get {
                return ResourceManager.GetString("ShowPlayersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать рамку в момент, когда можно нажимать на кнопку.
        /// </summary>
        public static string ShowQuestionBorder {
            get {
                return ResourceManager.GetString("ShowQuestionBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать правильные ответы.
        /// </summary>
        public static string ShowRightAnswers {
            get {
                return ResourceManager.GetString("ShowRightAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать заголовок на игровом табло.
        /// </summary>
        public static string ShowTableCaption {
            get {
                return ResourceManager.GetString("ShowTableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показывать текст вопросов при игре без фальстартов.
        /// </summary>
        public static string ShowTextNoFalseStartsHint {
            get {
                return ResourceManager.GetString("ShowTextNoFalseStartsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопросы СИ.
        /// </summary>
        public static string SIQuestions {
            get {
                return ResourceManager.GetString("SIQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка работы с библиотекой вопросов: {0}.
        /// </summary>
        public static string SIStorageError {
            get {
                return ResourceManager.GetString("SIStorageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Источник.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время на размышление над спецвопросом (с).
        /// </summary>
        public static string SpecialThinkingTime {
            get {
                return ResourceManager.GetString("SpecialThinkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ставка.
        /// </summary>
        public static string Stake {
            get {
                return ResourceManager.GetString("Stake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать игру.
        /// </summary>
        public static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить игру.
        /// </summary>
        public static string StopGame {
            get {
                return ResourceManager.GetString("StopGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вычесть сумму.
        /// </summary>
        public static string SubtractSum {
            get {
                return ResourceManager.GetString("SubtractSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить у активного игрока.
        /// </summary>
        public static string SubtractSumForActivePlayer {
            get {
                return ResourceManager.GetString("SubtractSumForActivePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма.
        /// </summary>
        public static string Sum {
            get {
                return ResourceManager.GetString("Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пакет тест.
        /// </summary>
        public static string TestPackage {
            get {
                return ResourceManager.GetString("TestPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарии темы.
        /// </summary>
        public static string ThemeComments {
            get {
                return ResourceManager.GetString("ThemeComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размышление.
        /// </summary>
        public static string Thinking {
            get {
                return ResourceManager.GetString("Thinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время на размышление после нажатия кнопки (с).
        /// </summary>
        public static string ThinkingTime {
            get {
                return ResourceManager.GetString("ThinkingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неизвестный тип.
        /// </summary>
        public static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Видео.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окно.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверных.
        /// </summary>
        public static string WrongAnswers {
            get {
                return ResourceManager.GetString("WrongAnswers", resourceCulture);
            }
        }
    }
}
