name: SIQuester release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SIQuester.sln
    - name: Publish x64
      run: dotnet publish src\SIQuester\SIQuester\SIQuester.csproj -c Release -p:PublishSingleFile=true -r win-x64 --self-contained true -p:EnableCompressionInSingleFile=true /property:Version=5.8.1
    - name: Build MSI x64
      run: msbuild deploy\SIQuester.Setup\SIQuester.Setup.wixproj /p:Configuration=Release /p:Platform=$platform /p:OutputPath=../../bin/.Release/SIQuester.Setup/x64 /p:BuildProjectReferences=false /p:MsiProductVersion=5.8.1
    - name: Build Setup
      run: msbuild deploy\SIQuester.Bootstrapper\SIQuester.Bootstrapper.wixproj /p:Configuration=Release /p:OutputPath=../../bin/.Release/SIQuester.Bootstrapper /p:BuildProjectReferences=false /p:MsiProductVersion=5.8.1
